application:
  actions: src/actions
  runtimeManifest:
    packages:
      a2b-brand:
        license: Apache-2.0
        actions:
          agency-event-handler:
            function: src/actions/agency-event-handler/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              S2S_API_KEY: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
            annotations:
              require-adobe-auth: false
              final: true
          agency-assetsynch-event-handler:
            function: src/actions/agency-assetsynch-event-handler/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              S2S_API_KEY: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
            annotations:
              require-adobe-auth: true
              final: true
extensions:
  dx/excshell/1:
    $include: src/dx-excshell-1/ext.config.yaml