application:
  actions: src/actions
  runtimeManifest:
    packages:
      a2b-brand:
        license: Apache-2.0
        actions:
          agency-event-handler:
            function: src/actions/event-handlers/agency-event-handler/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              S2S_API_KEY: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"brand","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
              AIO_runtime_apihost: $AIO_runtime_apihost
              AIO_runtime_auth: $AIO_runtime_auth
              AIO_runtime_namespace: $AIO_runtime_namespace
              AIO_ASSET_SYNCH_TARGET_PROGRAM_ENVIRONMENT: $AIO_ASSET_SYNCH_TARGET_PROGRAM_ENVIRONMENT
              CONTENT_TYPE: $CONTENT_TYPE
              DESTINATION_FOLDER_ID: $DESTINATION_FOLDER_ID
            annotations:
              require-adobe-auth: false
              final: true
          adobe-product-event-handler:
            function: src/actions/event-handlers/product/adobe-product-event-handler/index.ts
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              S2S_API_KEY: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"${AIO_APP_NAME}"}'
              AIO_runtime_apihost: $AIO_runtime_apihost
              AIO_runtime_auth: $AIO_runtime_auth
              AIO_runtime_namespace: $AIO_runtime_namespace
            annotations:
              require-adobe-auth: false
              final: true
          agency-assetsync-internal-handler:
            function: src/actions/event-handlers/product/agency-assetsync-internal-handler/index.ts
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              ORG_ID: $ORG_ID
              S2S_API_KEY: $S2S_API_KEY
              S2S_CLIENT_ID: $S2S_CLIENT_ID
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"${AIO_APP_NAME}"}'
            annotations:
              require-adobe-auth: false
              final: true
          agency-registration-internal-handler:
            function: src/actions/event-handlers/agency-registration-internal-handler/index.ts
            web: 'no'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"${AIO_APP_NAME}"}'
            annotations:
              require-adobe-auth: false
              final: true
          get-agencies:
            function: src/actions/services/agency/get-agencies/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"brand","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          get-agency:
            function: src/actions/services/agency/get-agency/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          new-agency-registration:
            function: src/actions/services/agency/new-agency-registration/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
              AIO_runtime_namespace: $AIO_runtime_namespace
              AIO_ACTION_PACKAGE_NAME: $AIO_ACTION_PACKAGE_NAME
              AGENCY_BASE_URL: $AGENCY_BASE_URL
            annotations:
              require-adobe-auth: true
              final: true
          update-agency:
            function: src/actions/services/agency/update-agency/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          delete-agency:
            function: src/actions/services/agency/delete-agency/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"agency","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          list-workfront-companies:
            function: src/actions/services/workfront/list-workfront-companies/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
            annotations:
              require-adobe-auth: true
              final: true
          list-workfront-groups:
            function: src/actions/services/workfront/list-workfront-groups/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
            annotations:
              require-adobe-auth: true
              final: true
          configure-workfront:
            function: src/actions/services/workfront/configure-workfront/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"brand","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          manage-workfront-subscriptions:
            function: src/actions/services/workfront/manage-workfront-subscriptions/index.ts
            web: 'no'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              S2S_CLIENT_ID: $SERVICE_API_KEY
              S2S_CLIENT_SECRET: $S2S_CLIENT_SECRET
              S2S_SCOPES: $S2S_SCOPES
              ORG_ID: $ORG_ID
              APPLICATION_RUNTIME_INFO: '{"namespace":"${AIO_runtime_namespace}","app_name":"brand","action_package_name":"${AIO_ACTION_PACKAGE_NAME}"}'
            annotations:
              require-adobe-auth: true
              final: true
          list-app-events:
            function: src/actions/services/event-registry/app/list-app-events/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-app-event:
            function: src/actions/services/event-registry/app/get-app-event/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          list-product-events:
            function: src/actions/services/event-registry/product/list-product-events/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-product-event:
            function: src/actions/services/event-registry/product/get-product-event/index.ts
            web: 'yes'
            runtime: nodejs:20
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          list-product-routing-rules:
            function: src/actions/services/routing-rules/global/product/list-product-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-product-routing-rules:
            function: src/actions/services/routing-rules/global/product/get-product-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          create-product-routing-rule:
            function: src/actions/services/routing-rules/global/product/create-product-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          update-product-routing-rule:
            function: src/actions/services/routing-rules/global/product/update-product-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-product-routing-rule:
            function: src/actions/services/routing-rules/global/product/delete-product-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          list-app-routing-rules:
            function: src/actions/services/routing-rules/global/app/list-app-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-app-routing-rules:
            function: src/actions/services/routing-rules/global/app/get-app-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          create-app-routing-rule:
            function: src/actions/services/routing-rules/global/app/create-app-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          update-app-routing-rule:
            function: src/actions/services/routing-rules/global/app/update-app-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-app-routing-rule:
            function: src/actions/services/routing-rules/global/app/delete-app-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          list-agency-routing-rules:
            function: src/actions/services/routing-rules/agency/list-agency-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          get-agency-routing-rules:
            function: src/actions/services/routing-rules/agency/get-agency-routing-rules/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          create-agency-routing-rule:
            function: src/actions/services/routing-rules/agency/create-agency-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          update-agency-routing-rule:
            function: src/actions/services/routing-rules/agency/update-agency-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
          delete-agency-routing-rule:
            function: src/actions/services/routing-rules/agency/delete-agency-routing-rule/index.ts
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true
extensions:
  dx/excshell/1:
    $include: src/dx-excshell-1/ext.config.yaml
